#!/usr/bin/env bash
# Unit tests for .autoducks/core/config/apply-plugins.sh (plugin compiler)
# Run: bash test/unit-apply-plugins.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PASS=0
FAIL=0
pass() { echo "  ✅ $1"; PASS=$((PASS + 1)); }
fail() { echo "  ❌ $1"; FAIL=$((FAIL + 1)); }

# ── Scratch repo scaffolding ─────────────────────────────────────────────
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

# new_repo NAME — sets REPO to a fresh isolated repo dir carrying only the
# compiler script + an empty plugins[] config; returns via global REPO.
new_repo() {
  REPO="$SCRATCH/$1"
  mkdir -p "$REPO/.autoducks/core/config"
  cp "$REPO_ROOT/.autoducks/core/config/apply-plugins.sh" "$REPO/.autoducks/core/config/"
  cat > "$REPO/.autoducks/autoducks.json" <<'EOF'
{"plugins": []}
EOF
}

# set_plugins REPO JSON_ARRAY — overwrite the plugins[] config
set_plugins() {
  local repo="$1" arr="$2"
  jq --argjson p "$arr" '.plugins = $p' "$repo/.autoducks/autoducks.json" > "$repo/.autoducks/autoducks.json.tmp"
  mv "$repo/.autoducks/autoducks.json.tmp" "$repo/.autoducks/autoducks.json"
}

# make_plugin REPO NAME HOOKS_JSON_ARRAY ALLOWED_TOOLS_JSON_ARRAY — scaffolds
# a vendored plugin under .autoducks/plugins/<name> with an action.yml stub
# for each declared hook.
make_plugin() {
  local repo="$1" name="$2" hooks="$3" tools="$4"
  local dir="$repo/.autoducks/plugins/$name"
  mkdir -p "$dir"
  jq -n --arg n "$name" --argjson h "$hooks" --argjson t "$tools" \
    '{schemaVersion: 1, name: $n, version: "1.0.0", hooks: $h, allowedTools: $t}' > "$dir/plugin.json"
  local hp
  for hp in $(jq -r '.[]' <<<"$hooks"); do
    mkdir -p "$dir/hooks/$hp"
    cat > "$dir/hooks/$hp/action.yml" <<EOF
name: '$name $hp'
runs:
  using: 'composite'
  steps:
    - run: echo $name-$hp
      shell: bash
EOF
  done
}

run_compiler() { # $1 = repo dir; stdout/stderr captured to $2 (optional path)
  (cd "$1" && bash .autoducks/core/config/apply-plugins.sh)
}

echo "── zero-plugins no-op ──"
new_repo zero
if run_compiler "$REPO" >/tmp/apply-plugins-zero.log 2>&1; then
  pass "exits 0 with empty plugins[]"
else
  fail "nonzero exit with empty plugins[]"
fi
if [[ ! -d "$REPO/.github/actions" && ! -d "$REPO/.autoducks/providers/llm/claude/compiled" ]]; then
  pass "no aggregators / no compiled/ files written"
else
  fail "artifacts written for empty plugins[]"
fi

echo "── single plugin aggregator generation ──"
new_repo single
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '["developer-pre"]' '["Bash"]'
run_compiler "$REPO" >/tmp/apply-plugins-single.log 2>&1 || { fail "single-plugin run failed"; cat /tmp/apply-plugins-single.log; }
AGG="$REPO/.github/actions/autoducks/developer-pre/action.yml"
if [[ -f "$AGG" ]]; then
  pass "aggregator written for developer-pre"
else
  fail "aggregator not written for developer-pre"
fi
head -n1 "$AGG" | grep -qF "GENERATED BY autoducks apply-plugins.sh" && pass "generated header present" || fail "generated header missing"
grep -q "^# content-hash: [0-9a-f]\{64\}$" "$AGG" && pass "content hash present" || fail "content hash missing/malformed"
grep -qF "uses: ./.autoducks/plugins/alpha/hooks/developer-pre" "$AGG" && pass "single plugin sub-action wired" || fail "single plugin sub-action missing"
[[ ! -f "$REPO/.github/actions/autoducks/developer-post/action.yml" ]] && pass "non-contributed hook point left absent" || fail "unexpected aggregator for developer-post"

echo "── declared-order composition (two plugins, shared hook point) ──"
new_repo order
set_plugins "$REPO" '[
  {"name":"alpha","source":".autoducks/plugins/alpha","config":{}},
  {"name":"beta","source":".autoducks/plugins/beta","config":{}}
]'
make_plugin "$REPO" alpha '["developer-pre"]' '["Bash"]'
make_plugin "$REPO" beta '["developer-pre"]' '["Write"]'
run_compiler "$REPO" >/tmp/apply-plugins-order.log 2>&1 || { fail "two-plugin run failed"; cat /tmp/apply-plugins-order.log; }
AGG="$REPO/.github/actions/autoducks/developer-pre/action.yml"
ALPHA_LINE="$(grep -n "uses: ./.autoducks/plugins/alpha/hooks/developer-pre" "$AGG" | cut -d: -f1)"
BETA_LINE="$(grep -n "uses: ./.autoducks/plugins/beta/hooks/developer-pre" "$AGG" | cut -d: -f1)"
if [[ -n "$ALPHA_LINE" && -n "$BETA_LINE" && "$ALPHA_LINE" -lt "$BETA_LINE" ]]; then
  pass "aggregator invokes plugins in declared array order (alpha before beta)"
else
  fail "aggregator did not preserve declared array order"
fi
STEP_COUNT="$(grep -c "^    - name: 'plugin: " "$AGG")"
[[ "$STEP_COUNT" -eq 2 ]] && pass "exactly one step per contributing plugin" || fail "expected 2 plugin steps, got $STEP_COUNT"
for envvar in AUTODUCKS_AGENT AUTODUCKS_STAGE ISSUE_NUM REPO COMMENT_ID RUN_ID COMMENTER GH_TOKEN \
  BASE_BRANCH IS_PR AGENT_OUTCOME COMMENT_ISSUE_NUM DRY_RUN; do
  grep -q "$envvar: \${{ env.$envvar }}" "$AGG" && pass "hook contract forwards $envvar" || fail "hook contract missing $envvar"
done

echo "── re-running the compiler twice yields byte-identical artifacts ──"
cp -R "$REPO/.github" "$SCRATCH/order-github-before"
cp -R "$REPO/.autoducks/providers/llm/claude/compiled" "$SCRATCH/order-compiled-before" 2>/dev/null || mkdir -p "$SCRATCH/order-compiled-before"
run_compiler "$REPO" >/tmp/apply-plugins-order2.log 2>&1 || { fail "second run failed"; cat /tmp/apply-plugins-order2.log; }
if diff -r "$SCRATCH/order-github-before" "$REPO/.github" >/dev/null; then
  pass "second run: .github/actions byte-identical"
else
  fail "second run: .github/actions changed"
fi
if diff -r "$SCRATCH/order-compiled-before" "$REPO/.autoducks/providers/llm/claude/compiled" >/dev/null; then
  pass "second run: compiled/ byte-identical"
else
  fail "second run: compiled/ changed"
fi

echo "── allowed-tools delta emission ──"
TOOLS_FILE="$REPO/.autoducks/providers/llm/claude/compiled/developer.allowed-tools"
if [[ -f "$TOOLS_FILE" ]]; then
  EXPECTED=$'Bash\nWrite'
  ACTUAL="$(cat "$TOOLS_FILE")"
  [[ "$ACTUAL" == "$EXPECTED" ]] && pass "allowed-tools delta is exactly the sorted plugin union" || fail "allowed-tools delta mismatch: got [$ACTUAL]"
else
  fail "allowed-tools delta file not written"
fi
NON_TARGET="$REPO/.autoducks/providers/llm/claude/compiled/close.allowed-tools"
[[ ! -f "$NON_TARGET" ]] && pass "no allowed-tools file for a non-LLM/non-targeted point" || fail "unexpected allowed-tools file: $NON_TARGET"

echo "── duplicate MCP server name hard-fails ──"
new_repo dupmcp
set_plugins "$REPO" '[
  {"name":"alpha","source":".autoducks/plugins/alpha","config":{}},
  {"name":"beta","source":".autoducks/plugins/beta","config":{}}
]'
make_plugin "$REPO" alpha '[]' '[]'
make_plugin "$REPO" beta '[]' '[]'
jq '.mcpServers = ["shared"]' "$REPO/.autoducks/plugins/alpha/plugin.json" > "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" \
  && mv "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" "$REPO/.autoducks/plugins/alpha/plugin.json"
jq '.mcpServers = ["shared"]' "$REPO/.autoducks/plugins/beta/plugin.json" > "$REPO/.autoducks/plugins/beta/plugin.json.tmp" \
  && mv "$REPO/.autoducks/plugins/beta/plugin.json.tmp" "$REPO/.autoducks/plugins/beta/plugin.json"
mkdir -p "$REPO/.autoducks/plugins/alpha/claude" "$REPO/.autoducks/plugins/beta/claude"
echo '{"mcpServers":{"shared":{"command":"a"}}}' > "$REPO/.autoducks/plugins/alpha/claude/mcp.json"
echo '{"mcpServers":{"shared":{"command":"b"}}}' > "$REPO/.autoducks/plugins/beta/claude/mcp.json"
if run_compiler "$REPO" >/tmp/apply-plugins-dupmcp.log 2>&1; then
  fail "duplicate MCP server name did not fail"
else
  grep -qi "duplicate MCP server name" /tmp/apply-plugins-dupmcp.log && pass "duplicate MCP server name hard-fails with an actionable message" || fail "wrong error for duplicate MCP server name"
fi

echo "── conflicting env.<KEY> hard-fails ──"
new_repo conflictenv
set_plugins "$REPO" '[
  {"name":"alpha","source":".autoducks/plugins/alpha","config":{}},
  {"name":"beta","source":".autoducks/plugins/beta","config":{}}
]'
make_plugin "$REPO" alpha '[]' '[]'
make_plugin "$REPO" beta '[]' '[]'
mkdir -p "$REPO/.autoducks/plugins/alpha/claude" "$REPO/.autoducks/plugins/beta/claude"
echo '{"env":{"FOO":"1"}}' > "$REPO/.autoducks/plugins/alpha/claude/settings.patch.json"
echo '{"env":{"FOO":"2"}}' > "$REPO/.autoducks/plugins/beta/claude/settings.patch.json"
if run_compiler "$REPO" >/tmp/apply-plugins-conflictenv.log 2>&1; then
  fail "conflicting env.FOO did not fail"
else
  grep -qi "conflicting env" /tmp/apply-plugins-conflictenv.log && pass "conflicting env.<KEY> hard-fails with an actionable message" || fail "wrong error for conflicting env"
fi

echo "── plugin env/mcpServers override a base value (layered, no hard-fail) ──"
new_repo baseoverride
mkdir -p "$REPO/.autoducks/providers/llm/claude"
cat > "$REPO/.autoducks/providers/llm/claude/settings.json" <<'EOF'
{"env":{"SOME_KEY":"base-value"},"mcpServers":{"shared":{"command":"base"}}}
EOF
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
jq '.mcpServers = ["shared"]' "$REPO/.autoducks/plugins/alpha/plugin.json" > "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" \
  && mv "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" "$REPO/.autoducks/plugins/alpha/plugin.json"
mkdir -p "$REPO/.autoducks/plugins/alpha/claude"
echo '{"mcpServers":{"shared":{"command":"plugin"}}}' > "$REPO/.autoducks/plugins/alpha/claude/mcp.json"
echo '{"env":{"SOME_KEY":"plugin-value"}}' > "$REPO/.autoducks/plugins/alpha/claude/settings.patch.json"
run_compiler "$REPO" >/tmp/apply-plugins-baseoverride.log 2>&1 || { fail "base-override run failed"; cat /tmp/apply-plugins-baseoverride.log; }
COMPILED="$REPO/.autoducks/providers/llm/claude/compiled/developer.settings.json"
if [[ -f "$COMPILED" ]] && jq -e '.env.SOME_KEY == "plugin-value"' "$COMPILED" >/dev/null 2>&1; then
  pass "plugin env overrides a base-defined env value without hard-failing"
else
  fail "plugin env did not override base env value"
fi
if [[ -f "$COMPILED" ]] && jq -e '.mcpServers.shared.command == "plugin"' "$COMPILED" >/dev/null 2>&1; then
  pass "plugin mcpServers entry overrides a base-defined mcpServers entry without hard-failing"
else
  fail "plugin mcpServers entry did not override base mcpServers entry"
fi

echo "── settings.patch.json mcpServers/hooks bypass is stripped (dedicated channels only) ──"
new_repo patchbypass
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
mkdir -p "$REPO/.autoducks/plugins/alpha/claude"
cat > "$REPO/.autoducks/plugins/alpha/claude/settings.patch.json" <<'EOF'
{"mcpServers":{"sneaky":{"command":"x"}},"hooks":{"PreToolUse":[{"matcher":"*","hooks":[{"type":"command","command":"sneaky"}]}]}}
EOF
run_compiler "$REPO" >/tmp/apply-plugins-patchbypass.log 2>&1 || { fail "patch-bypass run failed"; cat /tmp/apply-plugins-patchbypass.log; }
COMPILED="$REPO/.autoducks/providers/llm/claude/compiled/developer.settings.json"
if [[ -f "$COMPILED" ]] && ! jq -e '.mcpServers.sneaky' "$COMPILED" >/dev/null 2>&1; then
  pass "settings.patch.json mcpServers is ignored by the rest-merge"
else
  fail "settings.patch.json mcpServers leaked into compiled settings"
fi
if [[ -f "$COMPILED" ]] && ! jq -e '.hooks.PreToolUse' "$COMPILED" >/dev/null 2>&1; then
  pass "settings.patch.json hooks is ignored by the rest-merge"
else
  fail "settings.patch.json hooks leaked into compiled settings"
fi

echo "── plugin 'model' patch hard-fails ──"
new_repo modelset
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
mkdir -p "$REPO/.autoducks/plugins/alpha/claude"
echo '{"model":"claude-opus"}' > "$REPO/.autoducks/plugins/alpha/claude/settings.patch.json"
if run_compiler "$REPO" >/tmp/apply-plugins-modelset.log 2>&1; then
  fail "'model' patch did not fail"
else
  grep -qi "'model'" /tmp/apply-plugins-modelset.log && pass "plugin 'model' patch hard-fails with an actionable message" || fail "wrong error for 'model' patch"
fi

echo "── floating github: ref refused ──"
new_repo floating
set_plugins "$REPO" '[{"name":"gamma","source":"github:acme/gamma@main","config":{}}]'
if run_compiler "$REPO" >/tmp/apply-plugins-floating.log 2>&1; then
  fail "floating ref did not fail"
else
  grep -qi "floating ref" /tmp/apply-plugins-floating.log && pass "floating github: ref hard-fails with an actionable message" || fail "wrong error for floating ref"
fi

echo "── plugin colliding with a hand-authored hook refuses to touch it ──"
new_repo collide
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '["developer-post"]' '[]'
mkdir -p "$REPO/.github/actions/autoducks/developer-post"
cat > "$REPO/.github/actions/autoducks/developer-post/action.yml" <<'EOF'
name: 'hand authored'
runs:
  using: 'composite'
  steps: []
EOF
if run_compiler "$REPO" >/tmp/apply-plugins-collide.log 2>&1; then
  fail "collision with hand-authored hook did not fail"
else
  grep -qi "@local/hooks/developer-post" /tmp/apply-plugins-collide.log && pass "collision hard-fails and tells the user to relocate into @local" || fail "wrong error for hand-authored collision"
fi

echo "── hand-authored hook with no plugin contribution is left untouched ──"
new_repo untouched
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '["developer-pre"]' '[]'
mkdir -p "$REPO/.github/actions/autoducks/developer-post"
cat > "$REPO/.github/actions/autoducks/developer-post/action.yml" <<'EOF'
name: 'hand authored'
runs:
  using: 'composite'
  steps: []
EOF
cp "$REPO/.github/actions/autoducks/developer-post/action.yml" "$SCRATCH/untouched-before.yml"
run_compiler "$REPO" >/tmp/apply-plugins-untouched.log 2>&1 || { fail "untouched run failed"; cat /tmp/apply-plugins-untouched.log; }
diff -q "$SCRATCH/untouched-before.yml" "$REPO/.github/actions/autoducks/developer-post/action.yml" >/dev/null \
  && pass "hand-authored hook with no plugin contribution left byte-identical" \
  || fail "hand-authored hook with no plugin contribution was modified"

echo "── check/dry-run output-root mode does not touch the committed tree ──"
new_repo dryrun
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '["developer-pre"]' '["Bash"]'
OUTROOT="$SCRATCH/dryrun-out"
(cd "$REPO" && AUTODUCKS_APPLY_PLUGINS_OUTPUT_ROOT="$OUTROOT" bash .autoducks/core/config/apply-plugins.sh) >/tmp/apply-plugins-dryrun.log 2>&1 \
  || { fail "dry-run mode failed"; cat /tmp/apply-plugins-dryrun.log; }
if [[ ! -e "$REPO/.github" ]]; then
  pass "dry-run mode does not write into the committed tree"
else
  fail "dry-run mode wrote into the committed tree"
fi
if [[ -f "$OUTROOT/.github/actions/autoducks/developer-pre/action.yml" ]]; then
  pass "dry-run mode writes the same artifact under the output root"
else
  fail "dry-run mode did not write the expected artifact under the output root"
fi

echo "── non-vendored './' source resolves aggregator uses: to the actual path ──"
new_repo relsource
mkdir -p "$REPO/other/path/hooks/developer-pre"
jq -n '{schemaVersion:1,name:"gamma",version:"1.0.0",hooks:["developer-pre"],allowedTools:[]}' > "$REPO/other/path/plugin.json"
cat > "$REPO/other/path/hooks/developer-pre/action.yml" <<'EOF'
name: 'gamma developer-pre'
runs:
  using: 'composite'
  steps:
    - run: echo gamma
      shell: bash
EOF
set_plugins "$REPO" '[{"name":"gamma","source":"./other/path","config":{}}]'
run_compiler "$REPO" >/tmp/apply-plugins-relsource.log 2>&1 || { fail "non-vendored source run failed"; cat /tmp/apply-plugins-relsource.log; }
AGG="$REPO/.github/actions/autoducks/developer-pre/action.yml"
grep -qF "uses: ./other/path/hooks/developer-pre" "$AGG" \
  && pass "aggregator uses: resolves to the actual non-vendored source path" \
  || fail "aggregator uses: did not resolve to the non-vendored source path"

echo "── plugin Claude Code hook merges into compiled settings ──"
new_repo hooksmerge
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
jq '.claudeHooks = ["PreToolUse"]' "$REPO/.autoducks/plugins/alpha/plugin.json" > "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" \
  && mv "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" "$REPO/.autoducks/plugins/alpha/plugin.json"
mkdir -p "$REPO/.autoducks/plugins/alpha/claude"
cat > "$REPO/.autoducks/plugins/alpha/claude/hooks.json" <<'EOF'
{"hooks":{"PreToolUse":[{"matcher":"mcp__alpha__.*","hooks":[{"type":"command","command":"echo alpha"}]}]}}
EOF
run_compiler "$REPO" >/tmp/apply-plugins-hooksmerge.log 2>&1 || { fail "hooks-merge run failed"; cat /tmp/apply-plugins-hooksmerge.log; }
COMPILED="$REPO/.autoducks/providers/llm/claude/compiled/developer.settings.json"
if [[ -f "$COMPILED" ]] && jq -e '.hooks.PreToolUse[0].matcher == "mcp__alpha__.*"' "$COMPILED" >/dev/null 2>&1; then
  pass "plugin PreToolUse hook merges into compiled/<agent>.settings.json under .hooks"
else
  fail "plugin PreToolUse hook missing from compiled settings"
fi

echo "── declared claudeHooks event with no matching hooks.json entry fails validation ──"
new_repo crossvalidate
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
jq '.claudeHooks = ["PreToolUse"]' "$REPO/.autoducks/plugins/alpha/plugin.json" > "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" \
  && mv "$REPO/.autoducks/plugins/alpha/plugin.json.tmp" "$REPO/.autoducks/plugins/alpha/plugin.json"
if run_compiler "$REPO" >/tmp/apply-plugins-crossvalidate.log 2>&1; then
  fail "declared claudeHooks with no matching hooks.json entry did not fail"
else
  grep -qi "declares claudeHooks 'PreToolUse' but claude/hooks.json has no matching entry" /tmp/apply-plugins-crossvalidate.log \
    && pass "declared-but-missing claudeHooks entry fails validation with an actionable message" \
    || fail "wrong error for missing claudeHooks entry"
fi

echo "── mcp.json entry with no manifest 'mcpServers' declaration fails validation ──"
new_repo crossvalidate2
set_plugins "$REPO" '[{"name":"alpha","source":".autoducks/plugins/alpha","config":{}}]'
make_plugin "$REPO" alpha '[]' '[]'
mkdir -p "$REPO/.autoducks/plugins/alpha/claude"
echo '{"mcpServers":{"undeclared":{"command":"x"}}}' > "$REPO/.autoducks/plugins/alpha/claude/mcp.json"
if run_compiler "$REPO" >/tmp/apply-plugins-crossvalidate2.log 2>&1; then
  fail "undeclared mcpServers entry did not fail"
else
  grep -qi "claude/mcp.json defines server 'undeclared' but manifest 'mcpServers' does not declare it" /tmp/apply-plugins-crossvalidate2.log \
    && pass "mcp.json entry with no manifest declaration fails validation with an actionable message" \
    || fail "wrong error for undeclared mcpServers entry"
fi

echo ""
echo "═══ apply-plugins: $PASS passed, $FAIL failed ═══"
[[ "$FAIL" -eq 0 ]] || exit 1
